# Generated by Django 2.1.5 on 2020-02-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MailTo', models.CharField(max_length=50, verbose_name='Почта получателя')),
                ('MailFrom', models.CharField(max_length=50, verbose_name='Почта отправителя')),
                ('MailText', models.TextField(verbose_name='Текст сообщения')),
            ],
        ),
    ]
